#ifndef		__PT3_COM_H__
#define		__PT3_COM_H__

#define BIT_SHIFT_MASK(value, shift, mask) (((value) >> (shift)) & ((1<<(mask))-1))

#define		MAX_TUNER			2		//チューナ数
#define		MAX_CHANNEL			4		// チャネル数
#define		FALSE		0
#define		TRUE		1

typedef struct _BAR {
	unsigned long	mmio_start ;
	__u32			mmio_len ;
	void __iomem		*regs;
} BAR;

enum {
	PT3_ISDB_S,
	PT3_ISDB_T,
};

typedef enum {
	PT3_TS_PIN_MODE_NORMAL,
	PT3_TS_PIN_MODE_LOW,
	PT3_TS_PIN_MODE_HIGH,
} PT3_TS_PIN_MODE;

typedef struct _TS_PINS_MODE {
	int clock_data;
	int byte;
	int valid;
} PT3_TS_PINS_MODE;

typedef struct _TS_PINS_LEVEL {
	int clock;
	int data;
	int byte;
	int valid;
} PT3_TS_PINS_LEVEL;

typedef enum {
	// エラーなし
	STATUS_OK,

	// 一般的なエラー
	STATUS_GENERAL_ERROR = (1)*0x100,
	STATUS_NOT_IMPLIMENTED,
	STATUS_INVALID_PARAM_ERROR,
	STATUS_OUT_OF_MEMORY_ERROR,
	STATUS_INTERNAL_ERROR,

	// バスクラスのエラー
	STATUS_WDAPI_LOAD_ERROR = (2)*256,	// wdapi1100.dll がロードできない
	STATUS_ALL_DEVICES_MUST_BE_DELETED_ERROR,

	// デバイスクラスのエラー
	STATUS_PCI_BUS_ERROR = (3)*0x100,
	STATUS_CONFIG_REVISION_ERROR,
	STATUS_FPGA_VERSION_ERROR,
	STATUS_PCI_BASE_ADDRESS_ERROR,
	STATUS_FLASH_MEMORY_ERROR,

	STATUS_DCM_LOCK_TIMEOUT_ERROR,
	STATUS_DCM_SHIFT_TIMEOUT_ERROR,

	STATUS_POWER_RESET_ERROR,
	STATUS_I2C_ERROR,
	STATUS_TUNER_IS_SLEEP_ERROR,

	STATUS_PLL_OUT_OF_RANGE_ERROR,
	STATUS_PLL_LOCK_TIMEOUT_ERROR,

	STATUS_VIRTUAL_ALLOC_ERROR,
	STATUS_DMA_ADDRESS_ERROR,
	STATUS_BUFFER_ALREADY_ALLOCATED_ERROR,

	STATUS_DEVICE_IS_ALREADY_OPEN_ERROR,
	STATUS_DEVICE_IS_NOT_OPEN_ERROR,

	STATUS_BUFFER_IS_IN_USE_ERROR,
	STATUS_BUFFER_IS_NOT_ALLOCATED_ERROR,

	STATUS_DEVICE_MUST_BE_CLOSED_ERROR,

	// WinDriver 関連のエラー
	STATUS_WD_DriverName_ERROR = (4)*0x100,

	STATUS_WD_Open_ERROR,
	STATUS_WD_Close_ERROR,

	STATUS_WD_Version_ERROR,
	STATUS_WD_License_ERROR,

	STATUS_WD_PciScanCards_ERROR,

	STATUS_WD_PciConfigDump_ERROR,

	STATUS_WD_PciGetCardInfo_ERROR,
	STATUS_WD_PciGetCardInfo_Bus_ERROR,
	STATUS_WD_PciGetCardInfo_Memory_ERROR,

	STATUS_WD_CardRegister_ERROR,
	STATUS_WD_CardUnregister_ERROR,

	STATUS_WD_CardCleanupSetup_ERROR,

	STATUS_WD_DMALock_ERROR,
	STATUS_WD_DMAUnlock_ERROR,

	STATUS_WD_DMASyncCpu_ERROR,
	STATUS_WD_DMASyncIo_ERROR,

	// ROM
	STATUS_ROM_ERROR = (5)*0x100,
	STATUS_ROM_TIMEOUT
} STATUS;

#endif
